version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Vidfetch
    ports:
      - 8000:8000
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A Vidfetch worker --pool=solo -l info
    volumes:
      - .:/Vidfetch
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A Vidfetch beat -l info
    volumes:
      - .:/Vidfetch
    environment:
      - DEBUG=0
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
