# Generated by Django 4.2.9 on 2024-01-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_title', models.CharField(max_length=100)),
                ('thumbnail_medium_url', models.URLField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
